name: is_even
description: Minimalist and elegant API that returns true if the given number is even.
version: 1.0.1
homepage: https://github.com/arnemolland/is_even

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  is_odd: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
